// Code generated by "stringer -type=OpCode"; DO NOT EDIT.

package vm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INVALID-0]
	_ = x[PUSH-1]
	_ = x[POP-2]
	_ = x[ADD-3]
	_ = x[SUB-4]
	_ = x[MUL-5]
	_ = x[DIV-6]
	_ = x[DECLARE-7]
	_ = x[STORE-8]
	_ = x[LOAD-9]
	_ = x[JUMP-10]
	_ = x[JUMP_F-11]
	_ = x[ENTER-12]
	_ = x[LEAVE-13]
	_ = x[CALL-14]
	_ = x[RET-15]
}

const _OpCode_name = "INVALIDPUSHPOPADDSUBMULDIVDECLARESTORELOADJUMPJUMP_FENTERLEAVECALLRET"

var _OpCode_index = [...]uint8{0, 7, 11, 14, 17, 20, 23, 26, 33, 38, 42, 46, 52, 57, 62, 66, 69}

func (i OpCode) String() string {
	if i >= OpCode(len(_OpCode_index)-1) {
		return "OpCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpCode_name[_OpCode_index[i]:_OpCode_index[i+1]]
}
