// Code generated by "stringer -type=TypeId"; DO NOT EDIT.

package vm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Invalid-0]
	_ = x[Any-1]
	_ = x[Int-2]
	_ = x[Float-3]
	_ = x[Bool-4]
	_ = x[Function-5]
	_ = x[Array-6]
	_ = x[ExternalFunction-7]
}

const _TypeId_name = "InvalidAnyIntFloatBoolFunctionArrayExternalFunction"

var _TypeId_index = [...]uint8{0, 7, 10, 13, 18, 22, 30, 35, 51}

func (i TypeId) String() string {
	if i >= TypeId(len(_TypeId_index)-1) {
		return "TypeId(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TypeId_name[_TypeId_index[i]:_TypeId_index[i+1]]
}
